# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/blog/mobile-and-browser-testing-on-circleci-simple-setup-easy-management-increased-confidence/ for more details
#
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.1
workflows:
  build:
    jobs:
      - cypress/run
