
defaults: &defaults
  working_directory: ~/src
  docker:
    - image: circleci/python:3.7.3-node

orbs:
  ruby: circleci/ruby@1.1.4
  aws-cli: circleci/aws-cli@2.0.3
version: 2.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - aws-cli/install
      - aws-cli/setup:
          aws-region: aws_region
          aws-access-key-id: aws_access_key_id
          aws_secret_access_key: aws_secret_access_key
      - run:
          name: disable strict host checking
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Check out and prepare utils repo
          command: |
            cd ~/
            mkdir circleci_orbs
            git clone git@github.com:Uclusion/circleci_orbs.git ./circleci_orbs
      - run:
          name: bless
          command: |
            cd ~/circleci_orbs/scripts
            ./test_user_deleter.rb --poolId=${pool_id}
      - run:
          name: Get the required npm modules and run Cypress tests
          command: |
            cd ~/src
            npm install
            ./node_modules/.bin/cypress run
      - run:
          name: install latest pip and python modules
          command: |
            sudo pip install --upgrade pip
            pip install --user PyGithub
      - run:
          name: bless
          command: |
            cd ~/circleci_orbs
            python -m scripts.test_and_bless -e ${env_name} -a ${github_token} -t ../nodejs_sdk -u true

workflows:
  test-stage:
    jobs:
      - test:
          filters:
            tags:
              only: /^stage_only.*/
            branches:
              ignore: /.*/
          context: stage