
defaults: &defaults
  working_directory: ~/src
  docker:
    - image: circleci/python:3.9-node

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  cypress: cypress-io/cypress@3
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node16.17.0-chrome106'
version: 2.1

jobs:
  prepare_ruby:
    working_directory: ~/src
    docker:
        - image: circleci/ruby:2.7
    parameters:
      emails:
        type: string
        default: ''
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-region: aws_region
          aws-access-key-id: aws_access_key_id
          aws-secret-access-key: aws_secret_access_key
      - run:
          name: disable strict host checking
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Check out and prepare utils repo
          command: |
            cd ~/
            mkdir circleci_orbs
            git clone git@github.com:Uclusion/circleci_orbs.git ./circleci_orbs
      - run:
          name: delete tusers from Cognito
          command: |
            cd ~/circleci_orbs/scripts
            ./test_user_deleter.rb --poolId=${pool_id} -e "<< parameters.emails >>"
  prepare_python:
    <<: *defaults
    parameters:
      emails:
        type: string
        default: ''
    steps:
      - run:
          name: disable strict host checking
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Check out and prepare utils repo
          command: |
            cd ~/
            mkdir circleci_orbs
            git clone git@github.com:Uclusion/circleci_orbs.git ./circleci_orbs
      - run:
          name: install latest pip and python modules
          command: |
            sudo pip install --upgrade pip
            pip install --user boto3
            pip install --user pynamodb
            pip install --user PyJWT
      - run:
          name: install keys
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            mkdir ~/.aws
            echo -e "[default]\naws_access_key_id=$aws_access_key_id\naws_secret_access_key=$aws_secret_access_key\n" > ~/.aws/credentials
      - run:
          name: delete tusers from Dynamodb
          command: |
            cd ~/circleci_orbs
            export ENV_NAME=${env_name}
            python -m scripts.cleanup_test_users -e "<< parameters.emails >>"
  record:
    <<: *defaults
    steps:
      - run:
          name: disable strict host checking
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Check out and prepare utils repo
          command: |
            cd ~/
            mkdir circleci_orbs
            git clone git@github.com:Uclusion/circleci_orbs.git ./circleci_orbs
      - run:
          name: install latest pip and python modules
          command: |
            sudo pip install --upgrade pip
            pip install --user PyGithub
      - run:
          name: bless
          command: |
            cd ~/circleci_orbs
            python -m scripts.test_and_bless -e ${env_name} -a ${github_token} -u true

workflows:
  test-stage:
    jobs:
      - prepare_ruby:
          filters:
            tags:
              only: /^stage_only.*/
            branches:
              ignore: /.*/
          context: stage
      - prepare_python:
          filters:
            tags:
              only: /^stage_only.*/
            branches:
              ignore: /.*/
          context: stage
      - cypress/run:
          requires:
            - prepare_ruby
            - prepare_python
          install-command: 'npm install --no-optional --unsafe-perm'
          working-directory: '.'
          filters:
            tags:
              only: /^stage_only.*/
            branches:
              ignore: /.*/
          context: stage
      - record:
          requires:
            - cypress/run
          filters:
            tags:
              only: /^stage_only.*/
            branches:
              ignore: /.*/
          context: stage
  clean-dev:
    jobs:
      - prepare_ruby:
          filters:
            tags:
              only: /^dev_only.*/
            branches:
              ignore: /.*/
          context: dev
      - prepare_python:
          filters:
            tags:
              only: /^dev_only.*/
            branches:
              ignore: /.*/
          context: dev
  clean-dev-specified:
    jobs:
      - prepare_ruby:
          emails: 'disrael@uclusion.com,support@uclusion.com,testeruclusion@gmail.com,production.amazon@uclusion.com,disrael@gmail.com'
          filters:
            tags:
              only: /^dev_specific.*/
            branches:
              ignore: /.*/
          context: dev
      - prepare_python:
          emails: 'disrael@uclusion.com,support@uclusion.com,testeruclusion@gmail.com,production.amazon@uclusion.com,disrael@gmail.com'
          filters:
            tags:
              only: /^dev_specific.*/
            branches:
              ignore: /.*/
          context: dev
  clean-stage-specified:
    jobs:
      - prepare_ruby:
          emails: 'david.israel@uclude.com,827hooshang@gmail.com'
          filters:
            tags:
              only: /^stage_specific.*/
            branches:
              ignore: /.*/
          context: stage
      - prepare_python:
          emails: 'david.israel@uclude.com,827hooshang@gmail.com'
          filters:
            tags:
              only: /^stage_specific.*/
            branches:
              ignore: /.*/
          context: stage
  clean-production-specified:
    jobs:
      - prepare_ruby:
          emails: 'olivier.tassinari@gmail.com'
          filters:
            tags:
              only: /^production_specific.*/
            branches:
              ignore: /.*/
          context: production
      - prepare_python:
          emails: 'olivier.tassinari@gmail.com'
          filters:
            tags:
              only: /^production_specific.*/
            branches:
              ignore: /.*/
          context: production
  clean-production:
    jobs:
      - prepare_ruby:
          filters:
            tags:
              only: /^production_only.*/
            branches:
              ignore: /.*/
          context: production
      - prepare_python:
          filters:
            tags:
              only: /^production_only.*/
            branches:
              ignore: /.*/
          context: production
