name: Test Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Clone build utils
        uses: actions/checkout@v4
        with:
          repository: 'Uclusion/circleci_orbs'
          token: ${{ secrets.GIT_TOKEN }}
          path: utils_repo
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        if: always() # Upload artifacts even if the Cypress run fails
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
      - name: Bless UI that was tested
        run: |
          npm install
          cd utils_repo/scripts
          ./test_user_deleter.rb --poolId=${{ secrets.POOL_ID }}
          cd ..
          pip install --user PyGithub
          python -m scripts.test_and_bless -e ${{ inputs.environment }} -a ${{ secrets.GIT_TOKEN }} -u true
